#line 2 "scanner.cpp"

#line 4 "scanner.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 99
#define YY_END_OF_BUFFER 100
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[263] =
    {   0,
        0,    0,    0,    0,  100,   98,   97,   96,   98,   77,
       94,   98,   86,   87,   92,   90,   85,   91,   78,   98,
       70,   70,   70,   95,   83,   79,   93,   80,   72,   12,
       72,   72,   55,    3,   72,   72,   72,   72,   10,   56,
       11,   72,   47,   38,   72,   72,    4,   72,   81,   82,
       84,   88,   89,   99,    0,   71,   77,   77,    0,    0,
        0,   75,   75,    0,   70,   72,   72,   72,   72,   72,
       72,   72,    7,   72,   72,   72,   72,   72,   48,   72,
       72,   72,   72,   72,   72,    8,   72,   22,   72,   72,
       20,   72,   72,   72,   68,   72,   72,   72,   50,   72,

       72,   72,   72,   72,   72,   67,   72,   72,   72,   72,
       72,   72,    9,   73,    0,    0,   75,   75,   75,   75,
       75,   76,   76,   25,   26,   17,   72,   72,   41,   72,
       72,   72,   72,   72,   72,   72,   72,   72,   72,   72,
       72,   72,   72,   34,   72,   72,   72,   59,   72,   72,
       72,   72,   72,   72,   72,   72,   33,   43,   45,   57,
       72,   72,   72,   72,   72,   72,   72,   37,   72,   32,
       74,   74,   76,   76,   76,   76,   76,   72,   72,   72,
       72,   72,   72,   40,   72,   49,   60,   44,   69,   23,
       72,   42,   51,   24,   72,   72,   72,   72,   72,   72,

       21,   72,   72,   72,   16,    5,   72,   72,   72,   72,
       58,    1,   66,   14,   72,   74,   74,   74,   74,   74,
       63,   72,   72,   53,   36,   52,   72,   13,   61,   72,
       27,   72,   46,   72,   72,   29,   31,   18,   54,   72,
       30,   35,   72,   72,   72,   15,   72,   28,    2,   39,
        6,   72,   72,   72,   72,   19,   65,   64,   72,   72,
       62,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    5,    6,    1,    1,    7,    8,
        9,   10,   11,   12,   13,   14,   15,   16,   16,   17,
       18,   16,   16,   16,   16,   16,   16,   19,   20,   21,
       22,   23,    1,    1,   24,   25,   26,   27,   28,   29,
       30,   31,   32,   33,   34,   35,   36,   37,   38,   39,
       40,   41,   42,   43,   44,   45,   46,   47,   48,   49,
       50,   51,   52,   53,   54,    1,   55,   56,   57,   58,

       59,   60,   61,   62,   63,   64,   65,   66,   67,   68,
       69,   70,   40,   71,   72,   73,   74,   75,   76,   77,
       78,   79,   80,    1,   81,    1,    1,    1,   40,    1,
        1,    1,    1,    1,    1,    1,   40,    1,    1,    1,
       40,    1,    1,    1,   40,    1,   40,    1,    1,    1,
        1,    1,    1,   40,    1,    1,    1,    1,    1,    1,
       40,    1,    1,    1,    1,    1,    1,    1,   40,    1,
        1,    1,   40,    1,    1,    1,   40,    1,   40,    1,
        1,    1,    1,    1,    1,   40,    1,    1,    1,    1,
        1,    1,    1,    1,   40,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[82] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    3,    4,    5,    5,    5,    1,    1,
        1,    1,    1,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    1,
        6,    1,    1,    7,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    1,
        1
    } ;

static const flex_int16_t yy_base[278] =
    {   0,
        0,    0,    0,    0,  114, 2170, 2170, 2170,   79,  108,
     2170,   68, 2170, 2170, 2170, 2170, 2170, 2170, 2170,   71,
       76,   81,   86, 2170, 2170, 2170, 2170, 2170,   91,  107,
      161,  134,  187,  251,  115,  141,  154,  219,  166,  232,
      312,  237,  317,  331,  326,  338,  383,  242, 2170, 2170,
     2170, 2170, 2170, 2170,  108, 2170,    0,  101,  110,  147,
      193,  412,  417,  121,  299,  394,  405,  422,  436,  429,
      444,  468,  451,  463,  456,  475,  495,  486,  520,  525,
      541,  552,  564,  572,  584,  591,  611,  603,  616,  636,
      642,  650,  655,  667,  677,  684,  742,  696,  719,  725,

      731,  764,  792,  790,  781,  809,  822,  827,  851,  856,
      861,  866,  875, 2170,  201,  208,  916,  924,  929,  934,
      939,  222,  282,  882,  944,  949,  955,  983,  968,  973,
      978,  988, 1007, 1012, 1035, 1040, 1059, 1065, 1081, 1098,
     1109, 1093, 1125, 1132, 1139, 1155, 1160, 1166, 1171, 1190,
     1201, 1219, 1229, 1240, 1234, 1253, 1260, 1268, 1284, 1292,
     1299, 1310, 1316, 1323, 1338, 1351, 1357, 1366, 1377, 1382,
      498,  624,  699,  747,  795,  959, 1001, 1390, 1405, 1411,
     1421, 1416, 1435, 1440, 1450, 1464, 1470, 1481, 1491, 1496,
     1503, 1511, 1516, 1522, 1530, 1537, 1545, 1563, 1555, 1569,

     1576, 1594, 1584, 1602, 1625, 1633, 1643, 1649, 1656, 1664,
     1676, 1682, 1690, 1695, 1706, 1052, 1113, 1184, 1195, 1303,
     1711, 1723, 1729, 1737, 1752, 1757, 1768, 1783, 1791, 1796,
     1801, 1814, 1807, 1824, 1846, 1830, 1853, 1859, 1865, 1874,
     1879, 1898, 1904, 1909, 1920, 1926, 1932, 1937, 1943, 1959,
     1965, 1971, 1976, 1988, 2004, 2010, 2015, 2021, 2034, 2043,
     2060, 2170, 2114, 2121, 2128, 2131,   96, 2135, 2140, 2145,
     2150,   91,   86, 2153, 2156, 2159, 2162
    } ;

static const flex_int16_t yy_def[278] =
    {   0,
      262,    1,  263,  263,  262,  262,  262,  262,  264,  265,
      262,  266,  262,  262,  262,  262,  262,  262,  262,  267,
      268,  268,  268,  262,  262,  262,  262,  262,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  262,  262,
      262,  262,  262,  262,  264,  262,  265,  265,  262,  266,
      266,  270,  271,  272,  268,  268,  268,  268,  268,  268,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,

      269,  269,  269,   97,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  262,  273,  267,  270,  270,  270,  270,
      271,  274,  275,  268,  268,  269,  269,  268,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      276,  277,  274,  274,  274,  274,  275,  269,  268,  268,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,

      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  276,  276,  276,  276,  277,
      269,  268,  268,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  268,  268,  269,  269,  269,  269,  269,
      269,  269,  268,  268,  269,  269,  268,  268,  269,  269,
      269,    0,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262
    } ;

static const flex_int16_t yy_nxt[2252] =
    {   0,
        6,    7,    8,    9,   10,   11,   12,   13,   14,   15,
       16,   17,   18,   19,   20,   21,   22,   23,   24,   25,
       26,   27,   28,   29,   30,   31,   32,   33,   34,   35,
       36,   37,   38,   39,   40,   41,   42,   36,   43,   36,
       44,   45,   46,   47,   36,   48,   36,   36,   36,   49,
        6,   50,   51,    6,   29,   30,   31,   32,   33,   34,
       35,   36,   37,   38,   39,   40,   41,   42,   36,   43,
       44,   45,   46,   47,   36,   48,   36,   36,   36,   52,
       53,   56,   56,   59,   59,   59,   62,   62,   62,   64,
      172,   65,   65,   65,   64,  123,   65,   65,   65,   64,

       63,   65,   65,   65,   64,   58,   70,   70,   70,   68,
       56,   56,   58,  262,   69,  262,  114,   72,   61,  262,
       64,  262,   70,   70,   70,   59,   59,   59,   64,   67,
       70,   70,   70,  262,   67,   73,  122,  122,  122,   67,
       68,   74,   75,  262,   67,   69,  262,   64,   72,   70,
       70,   70,  262,  114,   64,   90,   70,   70,   70,  262,
       67,   80,  262,  262,  262,   81,   73,   64,   67,   70,
       70,   70,   74,   75,   64,  262,   70,   70,   70,   64,
       91,   70,   70,   70,   76,   90,  262,   67,  262,  262,
       92,   77,   80,  262,   67,  262,   81,  262,   78,   79,

       64,  262,   70,   70,   70,  262,  262,   67,   59,   59,
       59,   91,  262,   82,   67,   76,  171,  171,  171,   67,
      262,   92,   77,   62,   62,   62,  262,  262,  262,   78,
       79,  262,   64,   83,   70,   70,   70,  173,  173,  173,
       67,  262,  262,  262,   82,   64,  262,   70,   70,   70,
       64,  262,   70,   70,   70,   64,   93,   70,   70,   70,
      100,  262,  262,   83,   64,  262,   70,   70,   70,   94,
      113,  262,   67,   95,   84,  175,  262,   85,  262,   86,
      262,  262,   87,  262,  262,   67,  262,   93,  262,  262,
       67,  100,   88,  262,   89,   67,  262,  176,  176,  176,

       94,  113,  262,   95,   67,   84,  262,  262,   85,  262,
       86,  262,   64,   87,   65,   65,   65,  262,  262,  262,
      262,  262,   88,  262,   89,   64,  262,   70,   70,   70,
       64,  262,   70,   70,   70,  175,   96,  262,  262,   64,
      101,   70,   70,   70,   64,   97,   70,   70,   70,   98,
      106,   64,   67,   70,   70,   70,   99,  107,  103,  262,
      262,  262,  102,  262,  262,   67,  104,   96,  262,  262,
       67,  101,  262,  262,  105,  262,   97,  262,  108,   67,
       98,  106,  262,  262,   67,  109,   99,  262,  107,  103,
      262,   67,  102,  262,  262,  262,   64,  104,   70,   70,

       70,  262,  262,  262,  105,  262,  262,   64,  108,   70,
       70,   70,  110,  262,  262,  109,  262,  262,   64,  111,
       70,   70,   70,  262,  112,  115,  116,  117,  117,  117,
      115,  116,  120,  120,  120,   64,   67,   70,   70,   70,
      262,  262,   64,  110,   70,   70,   70,   67,  262,   64,
      111,   70,   70,   70,  112,  262,  262,   64,   67,   70,
       70,   70,  262,  124,   64,  119,   70,   70,   70,   64,
      119,   70,   70,   70,  262,   67,   64,  125,   70,   70,
       70,   64,   67,   70,   70,   70,  262,  262,   64,   67,
       70,   70,   70,  124,  126,  262,  262,   67,  262,   64,

      127,   70,   70,   70,   67,  262,  262,  125,   64,  128,
       70,   70,   70,  216,  216,  216,   67,  129,  262,  262,
      262,   67,  133,  262,  130,  126,  262,  262,   67,  262,
      131,  127,  132,   64,  262,   70,   70,   70,   64,   67,
       70,   70,   70,  262,  262,  262,  262,  129,   67,  262,
      262,  218,  262,  133,   64,  130,   70,   70,   70,  134,
      262,  131,  262,  132,  262,   64,  135,   70,   70,   70,
      262,  262,  262,   67,  262,  262,  262,   64,   67,   70,
       70,   70,  136,  137,  262,   64,  262,   70,   70,   70,
      134,  138,  262,  262,   67,  262,  135,   64,  262,   70,

       70,   70,  262,  262,   64,   67,   70,   70,   70,  262,
      262,  262,  136,  139,  137,  140,   64,   67,   70,   70,
       70,  262,  138,  262,   64,   67,   70,   70,   70,   64,
      262,   70,   70,   70,  262,  262,  262,   67,  262,  219,
      219,  219,  262,  139,   67,  141,  140,  142,  262,   64,
      143,   70,   70,   70,  262,   64,   67,   70,   70,   70,
      262,  262,  262,   64,   67,   70,   70,   70,   64,   67,
       70,   70,   70,  262,  144,  262,  141,  218,  142,  262,
       64,  143,   70,   70,   70,  262,  262,  145,  262,   67,
       64,  262,   70,   70,   70,   67,  147,   64,  146,   70,

       70,   70,  262,   67,  262,  144,  262,  262,   67,   64,
      262,   70,   70,   70,  173,  173,  173,  262,  145,  262,
       67,  262,  262,  262,  148,  262,  262,  147,  146,  262,
       67,  262,   64,  262,   70,   70,   70,   67,   64,  153,
       70,   70,   70,  262,   64,  262,   70,   70,   70,   67,
      262,  262,  175,  262,  148,   64,  262,   70,   70,   70,
      154,  262,  176,  176,  176,  262,  262,  262,  149,  153,
      150,  151,   67,  155,  156,  262,  262,   64,   67,   70,
       70,   70,  262,  262,   67,  152,  262,  262,  262,  262,
      157,  154,  262,  262,   64,   67,   70,   70,   70,  149,

      175,  150,  151,  155,  156,   64,  262,   70,   70,   70,
      176,  176,  176,  262,  262,  152,  161,   67,   71,  162,
      262,  157,   64,  164,   70,   70,   70,  158,  159,  262,
      160,  262,  262,  163,   67,   64,  262,   70,   70,   70,
       64,  262,   70,   70,   70,   67,  262,  161,  175,   71,
      162,  262,  262,  164,  166,  262,  262,  262,  158,  159,
      262,  160,   67,  163,   64,  262,   70,   70,   70,   64,
      165,   70,   70,   70,   64,   67,   70,   70,   70,   64,
       67,   70,   70,   70,  262,  166,  262,  262,   64,  167,
       70,   70,   70,  168,  262,   64,  169,   70,   70,   70,

      165,  262,  262,  262,   67,  262,  170,  262,  262,   67,
      262,  262,  262,  262,   67,  262,  262,  262,  262,   67,
      167,  262,  262,  262,  168,  262,  262,  169,   67,  115,
      116,  117,  117,  117,  262,   67,  170,  115,  116,  120,
      120,  120,  115,  116,  120,  120,  120,  115,  116,  120,
      120,  120,  115,  116,  120,  120,  120,   64,  262,   70,
       70,   70,   64,  262,   70,   70,   70,  262,   64,  119,
       70,   70,   70,  262,  176,  176,  176,  119,  262,  262,
      178,   64,  119,   70,   70,   70,   64,  119,   70,   70,
       70,   64,  119,   70,   70,   70,   64,   67,   70,   70,

       70,   64,   67,   70,   70,   70,  262,  179,   67,  262,
      262,  178,  175,  181,  180,  182,  176,  176,  176,  262,
       64,   67,   70,   70,   70,   64,   67,   70,   70,   70,
      262,   67,  262,  183,  262,  262,   67,  262,  179,  185,
      262,   67,  262,  181,  262,  180,  182,  262,   64,  184,
       70,   70,   70,   64,  175,   70,   70,   70,  262,  262,
       67,  262,  262,  183,  262,   67,  262,  216,  216,  216,
      185,  262,   64,  187,   70,   70,   70,  186,   64,  184,
       70,   70,   70,  262,  262,  262,  262,  262,   67,  262,
      189,  262,  262,   67,   64,  262,   70,   70,   70,  262,

      262,  188,  262,  262,  187,  218,   64,  186,   70,   70,
       70,   64,   67,   70,   70,   70,  262,  262,   67,  193,
      262,  189,   64,  190,   70,   70,   70,  262,  219,  219,
      219,  188,  262,  262,   67,  262,  192,  262,   64,  191,
       70,   70,   70,  262,  262,   64,   67,   70,   70,   70,
      193,   67,   64,  190,   70,   70,   70,  262,  262,  194,
      262,  262,   67,  262,  262,  195,  218,  192,   64,  191,
       70,   70,   70,   64,  262,   70,   70,   70,   67,   64,
      262,   70,   70,   70,   64,   67,   70,   70,   70,  262,
      194,  197,   67,  262,  262,  196,  195,  198,  262,  219,

      219,  219,  199,   64,  262,   70,   70,   70,   67,  262,
      219,  219,  219,   67,   64,  262,   70,   70,   70,   67,
      262,  200,  197,  262,   67,  196,  262,  262,  198,  262,
      262,  201,   64,  199,   70,   70,   70,  218,  262,  262,
      262,  202,   64,   67,   70,   70,   70,   64,  218,   70,
       70,   70,  200,   64,   67,   70,   70,   70,  262,  262,
      203,  201,  262,  262,  206,  204,   64,  205,   70,   70,
       70,  202,   67,   64,  262,   70,   70,   70,  262,  262,
      262,   64,   67,   70,   70,   70,  262,   67,  262,  262,
      203,  262,  262,   67,  207,  206,  204,   64,  205,   70,

       70,   70,  262,  262,  262,   64,   67,   70,   70,   70,
      262,  262,   64,   67,   70,   70,   70,  262,  219,  219,
      219,   67,  262,   64,  207,   70,   70,   70,  262,   64,
      208,   70,   70,   70,  262,  262,   64,   67,   70,   70,
       70,  262,  262,  262,  262,   67,  211,  262,  262,  262,
      209,   64,   67,   70,   70,   70,  218,  210,  262,  262,
      262,  208,  262,   67,   64,  212,   70,   70,   70,   67,
       64,  262,   70,   70,   70,  262,   67,  211,  213,   64,
      209,   70,   70,   70,  214,  262,  262,  210,  262,  262,
       64,   67,   70,   70,   70,   64,  212,   70,   70,   70,

      262,  262,  262,   64,   67,   70,   70,   70,  262,  213,
       67,  262,  262,  262,  215,  214,  262,  262,   64,   67,
       70,   70,   70,  221,   64,  262,   70,   70,   70,   64,
       67,   70,   70,   70,   64,   67,   70,   70,   70,  222,
      262,  262,  225,   67,  262,  215,  262,  223,   64,  262,
       70,   70,   70,   64,  221,   70,   70,   70,   67,  224,
      262,  262,  262,   64,   67,   70,   70,   70,  262,   67,
      222,  226,  262,  225,   67,  262,  262,   64,  223,   70,
       70,   70,  262,   64,  262,   70,   70,   70,   67,  262,
      224,  262,  227,   67,   64,  262,   70,   70,   70,  262,

      262,  262,  226,   67,   64,  262,   70,   70,   70,   64,
      262,   70,   70,   70,  262,  262,   64,   67,   70,   70,
       70,  262,  227,   67,   64,  262,   70,   70,   70,   64,
      262,   70,   70,   70,   67,   64,  228,   70,   70,   70,
      262,  262,  262,   64,   67,   70,   70,   70,  262,   67,
       64,  262,   70,   70,   70,  262,   67,  229,   64,  262,
       70,   70,   70,  262,   67,  262,  262,  228,   64,   67,
       70,   70,   70,  230,  262,   67,   64,  262,   70,   70,
       70,  231,   64,   67,   70,   70,   70,  262,  229,   64,
       67,   70,   70,   70,  262,  233,  234,   64,   67,   70,

       70,   70,  262,  235,  230,  262,  232,   64,   67,   70,
       70,   70,  231,  262,  262,   64,   67,   70,   70,   70,
      262,  262,   67,  262,  237,  233,  234,  262,  262,   67,
      262,  262,  236,  262,  235,  262,  232,   67,   64,  262,
       70,   70,   70,  262,  238,  262,   64,   67,   70,   70,
       70,  262,  262,  262,  237,   67,   64,  262,   70,   70,
       70,  262,   64,  236,   70,   70,   70,  262,  262,   64,
      239,   70,   70,   70,  238,  262,  262,   64,   67,   70,
       70,   70,  262,  262,  262,  262,   67,  262,  262,   64,
      240,   70,   70,   70,  241,   64,   67,   70,   70,   70,

      262,  239,   67,   64,  242,   70,   70,   70,   64,   67,
       70,   70,   70,  262,  262,  262,  262,   67,  262,   64,
      240,   70,   70,   70,   64,  241,   70,   70,   70,   67,
      262,  262,  262,  262,  242,   67,   64,  262,   70,   70,
       70,  262,   64,   67,   70,   70,   70,  262,   67,  243,
       64,  262,   70,   70,   70,  262,  262,  262,  262,   67,
      244,  262,  262,  262,   67,   64,  245,   70,   70,   70,
       64,  262,   70,   70,   70,  262,   67,  262,  262,  243,
      262,   64,   67,   70,   70,   70,  262,  262,  262,  262,
       67,  244,  262,  262,  262,  246,   64,  245,   70,   70,

       70,  262,  262,  262,   64,   67,   70,   70,   70,   64,
       67,   70,   70,   70,   64,  262,   70,   70,   70,  247,
       64,   67,   70,   70,   70,  262,  246,   64,  262,   70,
       70,   70,  262,  262,  262,  262,   67,   64,  262,   70,
       70,   70,  262,   64,   67,   70,   70,   70,  262,   67,
      247,  262,  262,  262,   67,  262,  248,  249,  262,   64,
       67,   70,   70,   70,  262,  262,   64,   67,   70,   70,
       70,  262,   64,  250,   70,   70,   70,   67,   64,  262,
       70,   70,   70,   67,  262,  262,  248,   64,  249,   70,
       70,   70,   64,  262,   70,   70,   70,  262,  262,   67,

      262,  262,  262,  262,  250,  262,   67,  251,  262,  262,
      262,   64,   67,   70,   70,   70,  262,   64,   67,   70,
       70,   70,   64,  262,   70,   70,   70,   67,  262,  262,
      262,  262,   67,   64,  253,   70,   70,   70,  251,   64,
      252,   70,   70,   70,  262,   64,  254,   70,   70,   70,
       64,   67,   70,   70,   70,  262,   64,   67,   70,   70,
       70,  262,   67,  262,  262,  253,  255,  262,  262,  262,
      262,  252,   64,   67,   70,   70,   70,  254,   64,   67,
       70,   70,   70,  262,   64,   67,   70,   70,   70,   64,
       67,   70,   70,   70,  262,  262,   67,  255,  262,  262,

      262,   64,  262,   70,   70,   70,  262,  262,  262,  257,
      262,  262,   67,  256,  262,  258,  262,   64,   67,   70,
       70,   70,  262,   64,   67,   70,   70,   70,   64,   67,
       70,   70,   70,  262,   64,  259,   70,   70,   70,  262,
      257,   67,  262,  256,  262,  262,  258,   64,  262,   70,
       70,   70,  262,  262,  262,  262,   64,   67,   70,   70,
       70,  262,  262,   67,  262,  262,  259,  262,   67,  262,
      260,  262,  261,   64,   67,   70,   70,   70,  262,  262,
      262,  262,  262,  262,  262,  262,  262,   67,  262,  262,
      262,  262,  262,  262,  262,  262,   67,  262,  262,  262,

      262,  260,  262,  261,  262,  262,  262,  262,  262,  262,
      262,  262,  262,   67,   54,   54,   54,   54,   54,   54,
       54,   55,   55,   55,   55,   55,   55,   55,   57,  262,
       57,   57,   57,   57,   57,   60,   60,   66,  262,   66,
      262,   66,   71,  262,   71,  262,   71,  118,  118,  118,
      262,  118,  121,  121,  121,  262,  121,  174,  262,  174,
      177,  262,  177,  217,  262,  217,  220,  262,  220,    5,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,

      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262
    } ;

static const flex_int16_t yy_chk[2252] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    9,    9,   12,   12,   12,   20,   20,   20,   21,
      273,   21,   21,   21,   22,  272,   22,   22,   22,   23,

      267,   23,   23,   23,   29,   58,   29,   29,   29,   22,
       55,   55,   10,    5,   23,    0,   59,   29,   12,    0,
       30,    0,   30,   30,   30,   59,   59,   59,   35,   21,
       35,   35,   35,    0,   22,   30,   64,   64,   64,   23,
       22,   30,   30,    0,   29,   23,    0,   32,   29,   32,
       32,   32,    0,   60,   36,   35,   36,   36,   36,    0,
       30,   32,   60,   60,   60,   32,   30,   37,   35,   37,
       37,   37,   30,   30,   31,    0,   31,   31,   31,   39,
       37,   39,   39,   39,   31,   35,    0,   32,    0,    0,
       37,   31,   32,    0,   36,    0,   32,   60,   31,   31,

       33,    0,   33,   33,   33,    0,    0,   37,   61,   61,
       61,   37,    0,   33,   31,   31,  115,  115,  115,   39,
        0,   37,   31,  116,  116,  116,    0,    0,    0,   31,
       31,    0,   38,   33,   38,   38,   38,  122,  122,  122,
       33,    0,    0,   61,   33,   40,    0,   40,   40,   40,
       42,    0,   42,   42,   42,   48,   38,   48,   48,   48,
       42,    0,    0,   33,   34,    0,   34,   34,   34,   40,
       48,    0,   38,   40,   34,  122,    0,   34,    0,   34,
        0,    0,   34,    0,    0,   40,    0,   38,    0,    0,
       42,   42,   34,    0,   34,   48,    0,  123,  123,  123,

       40,   48,    0,   40,   34,   34,    0,    0,   34,    0,
       34,    0,   65,   34,   65,   65,   65,    0,    0,    0,
        0,    0,   34,    0,   34,   41,    0,   41,   41,   41,
       43,    0,   43,   43,   43,  123,   41,    0,    0,   45,
       43,   45,   45,   45,   44,   41,   44,   44,   44,   41,
       45,   46,   65,   46,   46,   46,   41,   45,   44,    0,
        0,    0,   43,    0,    0,   41,   44,   41,    0,    0,
       43,   43,    0,    0,   44,    0,   41,    0,   46,   45,
       41,   45,    0,    0,   44,   46,   41,    0,   45,   44,
        0,   46,   43,    0,    0,    0,   47,   44,   47,   47,

       47,    0,    0,    0,   44,    0,    0,   66,   46,   66,
       66,   66,   47,    0,    0,   46,    0,    0,   67,   47,
       67,   67,   67,    0,   47,   62,   62,   62,   62,   62,
       63,   63,   63,   63,   63,   68,   47,   68,   68,   68,
        0,    0,   70,   47,   70,   70,   70,   66,    0,   69,
       47,   69,   69,   69,   47,    0,    0,   71,   67,   71,
       71,   71,    0,   68,   73,   62,   73,   73,   73,   75,
       63,   75,   75,   75,    0,   68,   74,   69,   74,   74,
       74,   72,   70,   72,   72,   72,    0,    0,   76,   69,
       76,   76,   76,   68,   72,    0,    0,   71,    0,   78,

       74,   78,   78,   78,   73,    0,    0,   69,   77,   75,
       77,   77,   77,  171,  171,  171,   74,   76,    0,    0,
        0,   72,   78,    0,   77,   72,    0,    0,   76,    0,
       77,   74,   77,   79,    0,   79,   79,   79,   80,   78,
       80,   80,   80,    0,    0,    0,    0,   76,   77,    0,
        0,  171,    0,   78,   81,   77,   81,   81,   81,   80,
        0,   77,    0,   77,    0,   82,   80,   82,   82,   82,
        0,    0,    0,   79,    0,    0,    0,   83,   80,   83,
       83,   83,   81,   82,    0,   84,    0,   84,   84,   84,
       80,   83,    0,    0,   81,    0,   80,   85,    0,   85,

       85,   85,    0,    0,   86,   82,   86,   86,   86,    0,
        0,    0,   81,   84,   82,   85,   88,   83,   88,   88,
       88,    0,   83,    0,   87,   84,   87,   87,   87,   89,
        0,   89,   89,   89,    0,    0,    0,   85,    0,  172,
      172,  172,    0,   84,   86,   87,   85,   87,    0,   90,
       89,   90,   90,   90,    0,   91,   88,   91,   91,   91,
        0,    0,    0,   92,   87,   92,   92,   92,   93,   89,
       93,   93,   93,    0,   90,    0,   87,  172,   87,    0,
       94,   89,   94,   94,   94,    0,    0,   92,    0,   90,
       95,    0,   95,   95,   95,   91,   94,   96,   93,   96,

       96,   96,    0,   92,    0,   90,    0,    0,   93,   98,
        0,   98,   98,   98,  173,  173,  173,    0,   92,    0,
       94,    0,    0,    0,   96,    0,    0,   94,   93,    0,
       95,    0,   99,    0,   99,   99,   99,   96,  100,   98,
      100,  100,  100,    0,  101,    0,  101,  101,  101,   98,
        0,    0,  173,    0,   96,   97,    0,   97,   97,   97,
      100,    0,  174,  174,  174,    0,    0,    0,   97,   98,
       97,   97,   99,  101,  101,    0,    0,  102,  100,  102,
      102,  102,    0,    0,  101,   97,    0,    0,    0,    0,
      102,  100,    0,    0,  105,   97,  105,  105,  105,   97,

      174,   97,   97,  101,  101,  103,    0,  103,  103,  103,
      175,  175,  175,    0,    0,   97,  104,  102,  104,  104,
        0,  102,  106,  105,  106,  106,  106,  103,  103,    0,
      103,    0,    0,  104,  105,  107,    0,  107,  107,  107,
      108,    0,  108,  108,  108,  103,    0,  104,  175,  104,
      104,    0,    0,  105,  108,    0,    0,    0,  103,  103,
        0,  103,  106,  104,  109,    0,  109,  109,  109,  110,
      107,  110,  110,  110,  111,  107,  111,  111,  111,  112,
      108,  112,  112,  112,    0,  108,    0,    0,  113,  109,
      113,  113,  113,  110,    0,  124,  111,  124,  124,  124,

      107,    0,    0,    0,  109,    0,  112,    0,    0,  110,
        0,    0,    0,    0,  111,    0,    0,    0,    0,  112,
      109,    0,    0,    0,  110,    0,    0,  111,  113,  117,
      117,  117,  117,  117,    0,  124,  112,  118,  118,  118,
      118,  118,  119,  119,  119,  119,  119,  120,  120,  120,
      120,  120,  121,  121,  121,  121,  121,  125,    0,  125,
      125,  125,  126,    0,  126,  126,  126,    0,  127,  117,
      127,  127,  127,    0,  176,  176,  176,  118,    0,    0,
      127,  129,  119,  129,  129,  129,  130,  120,  130,  130,
      130,  131,  121,  131,  131,  131,  128,  125,  128,  128,

      128,  132,  126,  132,  132,  132,    0,  128,  127,    0,
        0,  127,  176,  130,  128,  131,  177,  177,  177,    0,
      133,  129,  133,  133,  133,  134,  130,  134,  134,  134,
        0,  131,    0,  132,    0,    0,  128,    0,  128,  134,
        0,  132,    0,  130,    0,  128,  131,    0,  135,  133,
      135,  135,  135,  136,  177,  136,  136,  136,    0,    0,
      133,    0,    0,  132,    0,  134,    0,  216,  216,  216,
      134,    0,  137,  136,  137,  137,  137,  135,  138,  133,
      138,  138,  138,    0,    0,    0,    0,    0,  135,    0,
      138,    0,    0,  136,  139,    0,  139,  139,  139,    0,

        0,  137,    0,    0,  136,  216,  142,  135,  142,  142,
      142,  140,  137,  140,  140,  140,    0,    0,  138,  142,
        0,  138,  141,  139,  141,  141,  141,    0,  217,  217,
      217,  137,    0,    0,  139,    0,  141,    0,  143,  140,
      143,  143,  143,    0,    0,  144,  142,  144,  144,  144,
      142,  140,  145,  139,  145,  145,  145,    0,    0,  143,
        0,    0,  141,    0,    0,  145,  217,  141,  146,  140,
      146,  146,  146,  147,    0,  147,  147,  147,  143,  148,
        0,  148,  148,  148,  149,  144,  149,  149,  149,    0,
      143,  147,  145,    0,    0,  146,  145,  147,    0,  218,

      218,  218,  149,  150,    0,  150,  150,  150,  146,    0,
      219,  219,  219,  147,  151,    0,  151,  151,  151,  148,
        0,  150,  147,    0,  149,  146,    0,    0,  147,    0,
        0,  150,  152,  149,  152,  152,  152,  218,    0,    0,
        0,  151,  153,  150,  153,  153,  153,  155,  219,  155,
      155,  155,  150,  154,  151,  154,  154,  154,    0,    0,
      152,  150,    0,    0,  155,  153,  156,  154,  156,  156,
      156,  151,  152,  157,    0,  157,  157,  157,    0,    0,
        0,  158,  153,  158,  158,  158,    0,  155,    0,    0,
      152,    0,    0,  154,  156,  155,  153,  159,  154,  159,

      159,  159,    0,    0,    0,  160,  156,  160,  160,  160,
        0,    0,  161,  157,  161,  161,  161,    0,  220,  220,
      220,  158,    0,  162,  156,  162,  162,  162,    0,  163,
      161,  163,  163,  163,    0,    0,  164,  159,  164,  164,
      164,    0,    0,    0,    0,  160,  164,    0,    0,    0,
      162,  165,  161,  165,  165,  165,  220,  163,    0,    0,
        0,  161,    0,  162,  166,  165,  166,  166,  166,  163,
      167,    0,  167,  167,  167,    0,  164,  164,  166,  168,
      162,  168,  168,  168,  167,    0,    0,  163,    0,    0,
      169,  165,  169,  169,  169,  170,  165,  170,  170,  170,

        0,    0,    0,  178,  166,  178,  178,  178,    0,  166,
      167,    0,    0,    0,  169,  167,    0,    0,  179,  168,
      179,  179,  179,  178,  180,    0,  180,  180,  180,  182,
      169,  182,  182,  182,  181,  170,  181,  181,  181,  179,
        0,    0,  182,  178,    0,  169,    0,  180,  183,    0,
      183,  183,  183,  184,  178,  184,  184,  184,  179,  181,
        0,    0,    0,  185,  180,  185,  185,  185,    0,  182,
      179,  183,    0,  182,  181,    0,    0,  186,  180,  186,
      186,  186,    0,  187,    0,  187,  187,  187,  183,    0,
      181,    0,  185,  184,  188,    0,  188,  188,  188,    0,

        0,    0,  183,  185,  189,    0,  189,  189,  189,  190,
        0,  190,  190,  190,    0,    0,  191,  186,  191,  191,
      191,    0,  185,  187,  192,    0,  192,  192,  192,  193,
        0,  193,  193,  193,  188,  194,  191,  194,  194,  194,
        0,    0,    0,  195,  189,  195,  195,  195,    0,  190,
      196,    0,  196,  196,  196,    0,  191,  195,  197,    0,
      197,  197,  197,    0,  192,    0,    0,  191,  199,  193,
      199,  199,  199,  196,    0,  194,  198,    0,  198,  198,
      198,  197,  200,  195,  200,  200,  200,    0,  195,  201,
      196,  201,  201,  201,    0,  199,  199,  203,  197,  203,

      203,  203,    0,  200,  196,    0,  198,  202,  199,  202,
      202,  202,  197,    0,    0,  204,  198,  204,  204,  204,
        0,    0,  200,    0,  203,  199,  199,    0,    0,  201,
        0,    0,  202,    0,  200,    0,  198,  203,  205,    0,
      205,  205,  205,    0,  204,    0,  206,  202,  206,  206,
      206,    0,    0,    0,  203,  204,  207,    0,  207,  207,
      207,    0,  208,  202,  208,  208,  208,    0,    0,  209,
      207,  209,  209,  209,  204,    0,    0,  210,  205,  210,
      210,  210,    0,    0,    0,    0,  206,    0,    0,  211,
      208,  211,  211,  211,  209,  212,  207,  212,  212,  212,

        0,  207,  208,  213,  210,  213,  213,  213,  214,  209,
      214,  214,  214,    0,    0,    0,    0,  210,    0,  215,
      208,  215,  215,  215,  221,  209,  221,  221,  221,  211,
        0,    0,    0,    0,  210,  212,  222,    0,  222,  222,
      222,    0,  223,  213,  223,  223,  223,    0,  214,  215,
      224,    0,  224,  224,  224,    0,    0,    0,    0,  215,
      222,    0,    0,    0,  221,  225,  223,  225,  225,  225,
      226,    0,  226,  226,  226,    0,  222,    0,    0,  215,
        0,  227,  223,  227,  227,  227,    0,    0,    0,    0,
      224,  222,    0,    0,    0,  227,  228,  223,  228,  228,

      228,    0,    0,    0,  229,  225,  229,  229,  229,  230,
      226,  230,  230,  230,  231,    0,  231,  231,  231,  230,
      233,  227,  233,  233,  233,    0,  227,  232,    0,  232,
      232,  232,    0,    0,    0,    0,  228,  234,    0,  234,
      234,  234,    0,  236,  229,  236,  236,  236,    0,  230,
      230,    0,    0,    0,  231,    0,  232,  234,    0,  235,
      233,  235,  235,  235,    0,    0,  237,  232,  237,  237,
      237,    0,  238,  235,  238,  238,  238,  234,  239,    0,
      239,  239,  239,  236,    0,    0,  232,  240,  234,  240,
      240,  240,  241,    0,  241,  241,  241,    0,    0,  235,

        0,    0,    0,    0,  235,    0,  237,  240,    0,    0,
        0,  242,  238,  242,  242,  242,    0,  243,  239,  243,
      243,  243,  244,    0,  244,  244,  244,  240,    0,    0,
        0,    0,  241,  245,  244,  245,  245,  245,  240,  246,
      243,  246,  246,  246,    0,  247,  245,  247,  247,  247,
      248,  242,  248,  248,  248,    0,  249,  243,  249,  249,
      249,    0,  244,    0,    0,  244,  247,    0,    0,    0,
        0,  243,  250,  245,  250,  250,  250,  245,  251,  246,
      251,  251,  251,    0,  252,  247,  252,  252,  252,  253,
      248,  253,  253,  253,    0,    0,  249,  247,    0,    0,

        0,  254,    0,  254,  254,  254,    0,    0,    0,  253,
        0,    0,  250,  252,    0,  254,    0,  255,  251,  255,
      255,  255,    0,  256,  252,  256,  256,  256,  257,  253,
      257,  257,  257,    0,  258,  255,  258,  258,  258,    0,
      253,  254,    0,  252,    0,    0,  254,  259,    0,  259,
      259,  259,    0,    0,    0,    0,  260,  255,  260,  260,
      260,    0,    0,  256,    0,    0,  255,    0,  257,    0,
      259,    0,  260,  261,  258,  261,  261,  261,    0,    0,
        0,    0,    0,    0,    0,    0,    0,  259,    0,    0,
        0,    0,    0,    0,    0,    0,  260,    0,    0,    0,

        0,  259,    0,  260,    0,    0,    0,    0,    0,    0,
        0,    0,    0,  261,  263,  263,  263,  263,  263,  263,
      263,  264,  264,  264,  264,  264,  264,  264,  265,    0,
      265,  265,  265,  265,  265,  266,  266,  268,    0,  268,
        0,  268,  269,    0,  269,    0,  269,  270,  270,  270,
        0,  270,  271,  271,  271,    0,  271,  274,    0,  274,
      275,    0,  275,  276,    0,  276,  277,    0,  277,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,

      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[100] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 
        };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexico.l"
#line 5 "lexico.l"
#include <iostream>
#include <QString>
#include "parser.h"
#include <string>
#include <QList>

int yylex();
void yyerror(const char *s);
int linea = 0;
int columna = 1;
int anterior = 0;
#line 1072 "scanner.cpp"

#line 1074 "scanner.cpp"

#define INITIAL 0
#define COM 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 35 "lexico.l"

#line 1292 "scanner.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 263 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 2170 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 36 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext); strcpy(yylval.TEXT, yytext);return psize;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 37 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return pmkdisk;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 38 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return pf;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 39 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return pu;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 40 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return ppath;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 41 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return prmdisk;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 42 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return pbf;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 43 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return pff;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 44 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return pwf;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 45 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return pk;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 46 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return pm;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 47 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return pb;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 48 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return pfdisk;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 49 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return ptype;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 50 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return pdelete;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 51 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return pname;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 52 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return padd;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 53 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return pmount;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 54 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return punmount;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 55 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return pid;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 56 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return pmkfs;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 57 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return pfs;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 58 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return pfast;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 59 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return pfull;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 60 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return p2fs;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 61 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return p3fs;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 62 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return plogin;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 63 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return plogout;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 64 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return pmkgrp;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 65 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return prmgrp;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 66 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return pmkusr;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 67 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return pusr;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 68 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return pwd;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 69 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return pgrp;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 70 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return prmusr;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 71 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return pchmod;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 72 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return pugo;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 73 "lexico.l"
{columna=columna+ anterior;  anterior = strlen (yytext);strcpy(yylval.TEXT, yytext);return pr;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 74 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return pmkfile;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 75 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return pcont;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 76 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return pcat;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 77 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return pfilen;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 78 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return prem;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 79 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return pedit;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 80 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return pren;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 81 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return pmkdir;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 82 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return pp;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 83 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return pcp;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 84 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return pdest;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 85 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return pmv;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 86 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return pfind;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 87 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return pchown;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 88 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return pchgrp;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 89 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return ppause;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 90 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return pe;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 91 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return pl;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 92 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return prep;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 93 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return pruta;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 94 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return pmbr;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 95 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return pdisk;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 96 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return pinode;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 97 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return pjournaling;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 98 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return pblock;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 99 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return pbm_inode;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 100 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return pbm_block;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 101 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return ptree;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 102 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return psb;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 103 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return pls;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 104 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return pexec;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 106 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return entero;}
	YY_BREAK
case 71:
/* rule 71 can match eol */
YY_RULE_SETUP
#line 107 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return cadena;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 108 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return identificador;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 109 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return caracter;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 110 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return ruta;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 111 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return ruta_carpeta;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 112 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return name2;}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 113 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return coment;}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 115 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return punto;}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 116 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return bracketabre;}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 117 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return bracketcierra;}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 118 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return corcheteabre;}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 119 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return corchetecierra;}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 120 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return puntocoma;}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 121 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return potencia;}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 122 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return coma;}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 123 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return parentesisabre;}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 124 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return parentesiscierra;}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 125 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return llaveabre;}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 126 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return llavecierra;}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 127 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return mas;}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 128 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return menos;}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 129 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return multiplicacion;}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 130 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return igual;}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 131 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return dolar;}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 132 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return dospuntos;}
	YY_BREAK
case 96:
/* rule 96 can match eol */
YY_RULE_SETUP
#line 134 "lexico.l"
{linea++; columna=0; anterior=0;}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 135 "lexico.l"
{ columna++; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 137 "lexico.l"
{
    std::cout<<"Error Lexico: "<<linea<<"\n";
}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 140 "lexico.l"
ECHO;
	YY_BREAK
#line 1858 "scanner.cpp"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COM):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 263 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 263 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 262);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 140 "lexico.l"
